name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildandroid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
        channel: stable

    # Initial build and test
    - run: flutter pub get

    # For the apk build to Github Packages
    - run: flutter build apk

    # Sign apk release.
    - name: Sign Android apk release
      id: sign_release_apk
      uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: build/app/outputs/flutter-apk/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

    # Publish apk to Github Packages.
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "latest apk build"
        files: build/app/outputs/flutter-apk/app-release-signed.apk

    # Build Android
    - run: flutter build appbundle

    # Publish Android
    - name: Sign Android release
      id: sign_release
      uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Publish Android build to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.banool.auslan_dictionary
        # releaseFile: ${{ steps.run_tests.outputs.signedReleaseFile }}
        releaseFile: build/app/outputs/bundle/release/app-release.aab
        track: internal
